# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/springreact
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=userspringreact
spring.datasource.password=userspringreact

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
